import { JobRawData } from '../types';

/**
 * 种子数据 —— MVP 阶段预置示例岗位
 * 确保平台上线时不为空，同时展示各维度筛选的效果
 */
export function seedJobs(): JobRawData[] {
  const now = new Date();
  const makeDate = (hoursAgo: number) => new Date(now.getTime() - hoursAgo * 3600 * 1000);

  const jobs: JobRawData[] = [
    {
      title: '高级后端开发工程师（Java）',
      companyName: '字节跳动',
      city: '北京',
      salaryMin: 35000, salaryMax: 60000, salarySource: 'company_labeled',
      companyType: '大厂', jobDirection: '后端',
      jdText: '负责抖音电商后端服务开发。要求：3年以上Java开发经验，精通Spring Boot、MySQL、Redis、Kafka，熟悉分布式系统设计。月薪35k-60k，16薪。',
      sourceUrl: 'https://job.bytedance.com', sourcePlatform: 'corporate',
      techStack: ['Java', 'Spring Boot', 'MySQL', 'Redis', 'Kafka'],
      publishedAt: makeDate(2),
    },
    {
      title: '前端开发工程师（React）',
      companyName: '阿里巴巴',
      city: '杭州',
      salaryMin: 25000, salaryMax: 45000, salarySource: 'company_labeled',
      companyType: '大厂', jobDirection: '前端',
      jdText: '参与淘宝前端架构升级。要求：2年以上React开发经验，熟悉TypeScript、Next.js，有大型项目性能优化经验优先。月薪25k-45k。',
      sourceUrl: 'https://job.alibaba.com', sourcePlatform: 'corporate',
      techStack: ['React', 'TypeScript', 'Next.js'],
      publishedAt: makeDate(5),
    },
    {
      title: 'Go后端工程师',
      companyName: '腾讯',
      city: '深圳',
      salaryMin: 30000, salaryMax: 55000, salarySource: 'system_inferred',
      companyType: '大厂', jobDirection: '后端',
      jdText: '微信支付核心系统开发。要求：精通Go语言，熟悉微服务架构，有高并发系统经验。月薪30k-55k。',
      sourceUrl: 'https://join.qq.com', sourcePlatform: 'corporate',
      techStack: ['Go', 'Docker', 'Kubernetes', 'Redis', 'MySQL'],
      publishedAt: makeDate(8),
    },
    {
      title: 'Python后端 + AI应用开发',
      companyName: '美团',
      city: '北京',
      salaryMin: 30000, salaryMax: 50000, salarySource: 'company_labeled',
      companyType: '大厂', jobDirection: 'AI&算法',
      jdText: '美团AI团队招聘Python后端，负责大模型应用落地。要求：熟悉Python、FastAPI、LangChain、LLM应用开发经验。月薪30k-50k。',
      sourceUrl: 'https://zhaopin.meituan.com', sourcePlatform: 'corporate',
      techStack: ['Python', 'FastAPI', 'LangChain', 'LLM', 'Kubernetes'],
      publishedAt: makeDate(1),
    },
    {
      title: '全栈开发工程师',
      companyName: '小红书',
      city: '上海',
      salaryMin: 28000, salaryMax: 48000, salarySource: 'system_inferred',
      companyType: '大厂', jobDirection: '全栈',
      jdText: '小红书内容平台全栈开发。技术栈：React + Node.js + Go，熟悉数据库设计和缓存策略。薪资面议。',
      sourceUrl: 'https://job.xiaohongshu.com', sourcePlatform: 'corporate',
      techStack: ['React', 'TypeScript', 'Go', 'Node.js', 'Redis', 'PostgreSQL'],
      publishedAt: makeDate(3),
    },
    {
      title: 'AI算法工程师（大模型方向）',
      companyName: '华为',
      city: '深圳',
      salaryMin: 40000, salaryMax: 70000, salarySource: 'company_labeled',
      companyType: '大厂', jobDirection: 'AI&算法',
      jdText: '华为云AI团队招聘大模型算法工程师。要求：硕士以上学历，熟悉Transformer架构、PyTorch，有LLM训练/微调经验。月薪40k-70k。',
      sourceUrl: 'https://career.huawei.com', sourcePlatform: 'corporate',
      techStack: ['Python', 'PyTorch', 'TensorFlow', 'Transformer', 'LLM'],
      publishedAt: makeDate(12),
    },
    {
      title: '数据开发工程师',
      companyName: '快手',
      city: '北京',
      salaryMin: 25000, salaryMax: 45000, salarySource: 'system_inferred',
      companyType: '大厂', jobDirection: '数据',
      jdText: '快手数据中台建设。要求：熟悉Hadoop/Spark/Flink，精通SQL，有数据仓库建模经验。月薪25k-45k，15薪。',
      sourceUrl: 'https://zhaopin.kuaishou.cn', sourcePlatform: 'corporate',
      techStack: ['Spark', 'Flink', 'Hadoop', 'Hive', 'Kafka'],
      publishedAt: makeDate(24),
    },
    {
      title: '测试开发工程师',
      companyName: '网易',
      city: '广州',
      salaryMin: 20000, salaryMax: 35000, salarySource: 'system_inferred',
      companyType: '大厂', jobDirection: '测试&运维',
      jdText: '网易游戏测试开发。要求：熟悉自动化测试框架，Python/Java至少精通一种，有性能测试经验优先。月薪20k-35k。',
      sourceUrl: 'https://hr.163.com', sourcePlatform: 'corporate',
      techStack: ['Python', 'Java', 'Jenkins', 'Docker'],
      publishedAt: makeDate(6),
    },
    {
      title: '中级Java开发工程师',
      companyName: '某知名互联网金融公司',
      city: '杭州',
      salaryMin: 18000, salaryMax: 30000, salarySource: 'system_inferred',
      companyType: '中型企业', jobDirection: '后端',
      jdText: '金融核心系统开发。要求：2年以上Java开发，熟悉Spring Cloud微服务体系，有支付或金融项目经验优先。月薪18k-30k。',
      sourceUrl: '', sourcePlatform: 'boss',
      techStack: ['Java', 'Spring Cloud', 'MyBatis', 'MySQL', 'Redis', 'RabbitMQ'],
      publishedAt: makeDate(4),
    },
    {
      title: 'Golang后台开发',
      companyName: '蔚来汽车',
      city: '上海',
      salaryMin: 25000, salaryMax: 45000, salarySource: 'company_labeled',
      companyType: '中型企业', jobDirection: '后端',
      jdText: '车联网平台后台开发。要求：3年Go开发经验，熟悉gRPC、Kubernetes、时序数据库。月薪25k-45k。',
      sourceUrl: '', sourcePlatform: 'boss',
      techStack: ['Go', 'gRPC', 'Kubernetes', 'Docker', 'InfluxDB'],
      publishedAt: makeDate(15),
    },
    {
      title: '前端开发（Vue技术栈）',
      companyName: '某AI创业公司',
      city: '北京',
      salaryMin: 15000, salaryMax: 25000, salarySource: 'system_inferred',
      companyType: '创业公司', jobDirection: '前端',
      jdText: 'AI产品前端开发。要求：1-3年Vue前端经验，熟悉Element UI，有数据可视化经验优先。月薪15k-25k，期权可谈。',
      sourceUrl: '', sourcePlatform: 'v2ex',
      techStack: ['Vue', 'JavaScript', 'TypeScript', 'ECharts'],
      publishedAt: makeDate(1),
    },
    {
      title: 'React Native 移动端开发',
      companyName: '某跨境电商平台',
      city: '深圳',
      salaryMin: 20000, salaryMax: 35000, salarySource: 'system_inferred',
      companyType: '中型企业', jobDirection: '移动端',
      jdText: '跨境电商App开发。要求：2年以上RN开发经验，熟悉iOS/Android双端发布流程。月薪20k-35k。',
      sourceUrl: '', sourcePlatform: 'liepin',
      techStack: ['React Native', 'TypeScript', 'Redux', 'iOS', 'Android'],
      publishedAt: makeDate(10),
    },
    {
      title: 'DevOps/SRE工程师',
      companyName: '某云服务创业公司',
      city: '成都',
      salaryMin: 18000, salaryMax: 30000, salarySource: 'system_inferred',
      companyType: '创业公司', jobDirection: '测试&运维',
      jdText: '云原生基础设施运维。要求：精通Kubernetes、Terraform、Prometheus/Grafana，有阿里云或AWS运维经验。月薪18k-30k。',
      sourceUrl: '', sourcePlatform: 'v2ex',
      techStack: ['Kubernetes', 'Docker', 'Terraform', 'Prometheus', 'Grafana', '阿里云'],
      publishedAt: makeDate(20),
    },
    {
      title: 'C++高性能计算工程师',
      companyName: '某自动驾驶公司',
      city: '北京',
      salaryMin: 35000, salaryMax: 60000, salarySource: 'company_labeled',
      companyType: '创业公司', jobDirection: 'AI&算法',
      jdText: '自动驾驶感知算法优化。要求：精通C++/CUDA，有GPU并行计算经验，熟悉TensorRT。月薪35k-60k。',
      sourceUrl: '', sourcePlatform: 'liepin',
      techStack: ['C++', 'CUDA', 'TensorRT', 'Python'],
      publishedAt: makeDate(36),
    },
    {
      title: '全栈工程师（React + Python）',
      companyName: '微软中国',
      city: '上海',
      salaryMin: 30000, salaryMax: 50000, salarySource: 'system_inferred',
      companyType: '外企', jobDirection: '全栈',
      jdText: 'Azure云服务前端/后端全栈开发。要求：React + Python/Go，英语流利。月薪30k-50k。',
      sourceUrl: '', sourcePlatform: 'corporate',
      techStack: ['React', 'Python', 'Go', 'Azure', 'TypeScript'],
      publishedAt: makeDate(7),
    },
    {
      title: 'Java后端（银行核心系统）',
      companyName: '中国工商银行',
      city: '北京',
      salaryMin: 18000, salaryMax: 25000, salarySource: 'system_inferred',
      companyType: '国企&央企', jobDirection: '后端',
      jdText: '银行核心系统开发维护。要求：本科以上，2年以上Java经验，熟悉Spring、Oracle数据库。月薪18k-25k，六险二金。',
      sourceUrl: '', sourcePlatform: 'boss',
      techStack: ['Java', 'Spring', 'Oracle', 'MyBatis'],
      publishedAt: makeDate(14),
    },
    {
      title: '数据分析师（偏工程）',
      companyName: '哔哩哔哩',
      city: '上海',
      salaryMin: 20000, salaryMax: 35000, salarySource: 'system_inferred',
      companyType: '大厂', jobDirection: '数据',
      jdText: 'B站数据平台建设。要求：精通SQL、Python，熟悉数据仓库建模，有ClickHouse/Doris使用经验优先。月薪20k-35k。',
      sourceUrl: '', sourcePlatform: 'boss',
      techStack: ['Python', 'SQL', 'ClickHouse', 'Spark', 'Flink'],
      publishedAt: makeDate(18),
    },
    {
      title: 'iOS开发工程师',
      companyName: '小米',
      city: '北京',
      salaryMin: 25000, salaryMax: 40000, salarySource: 'company_labeled',
      companyType: '大厂', jobDirection: '移动端',
      jdText: 'MIUI系统App开发。要求：3年以上iOS开发经验，精通Swift/ObjC，有性能优化经验。月薪25k-40k。',
      sourceUrl: '', sourcePlatform: 'corporate',
      techStack: ['Swift', 'Objective-C', 'Xcode', 'Git'],
      publishedAt: makeDate(9),
    },
    {
      title: 'Rust系统开发工程师',
      companyName: '某数据库创业公司',
      city: '杭州',
      salaryMin: 30000, salaryMax: 55000, salarySource: 'system_inferred',
      companyType: '创业公司', jobDirection: '后端',
      jdText: '分布式数据库内核开发。要求：精通Rust或C++，有数据库/存储系统开发经验，熟悉LSM-Tree/B+Tree。月薪30k-55k。',
      sourceUrl: '', sourcePlatform: 'v2ex',
      techStack: ['Rust', 'C++', 'Linux'],
      publishedAt: makeDate(48),
    },
    {
      title: '初级Java开发（校招/社招）',
      companyName: '用友网络',
      city: '北京',
      salaryMin: 10000, salaryMax: 18000, salarySource: 'company_labeled',
      companyType: '中型企业', jobDirection: '后端',
      jdText: '用友ERP系统开发。要求：1年以上Java经验或优秀应届生，熟悉Spring Boot、MySQL。月薪10k-18k。',
      sourceUrl: '', sourcePlatform: 'lagou',
      techStack: ['Java', 'Spring Boot', 'MySQL'],
      publishedAt: makeDate(3),
    },
  ];

  return jobs;
}
